# Dependencies
markdown:	redcarpet
# Permalinks
permalink:	/blog/:title

# Setup
baseurl: /Thinny/

title:		Mixed Media Studios
tagline:	'Instant Karma'
description:	'Your own personal animation studio'
url:		http://mixedmediastudios.org/
commentsystem:	google
disqus:		example

author:
  name:		'Mixed Media Studios'
  url:		http://www.mixedmediastudios.org/

paginate:	10

# Custom vars
icon:		/Thinny/assets/images/icon.png
cover:	https://lh4.googleusercontent.com/-d2_moJjARgs/VIzbGUwrF0I/AAAAAAAAAFg/J_500ckvaYc/w1920-h1080-no/cover.jpg
# /Thinny/assets/images/cover.jpg

social:
  - icon:	twitter
    url:	https://twitter.com/iancamporez
    desc:	Follow me on twitter

  - icon:	github
    url:	https://github.com/camporez
    desc:	Fork me on github

  - icon:	googleplus-alt
    url:	https://google.com/+IanCamporezBrunelli
    desc:	Add me on google+

  - icon:	feed
    url:	http://camporez.com/atom.xml
    desc:	Subscribe to my feed

menu:
  - title:	Home
    url:	/Thinny

  - title:	About
    url:	/Thinny/about

copyright:
  author:	Mixed Media Studios
  url:		http://www.mixedmediastudios.org
  type_title:	Some rights reserved
  type_url:	http://creativecommons.org/licenses/by-nc/2.5

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics:

# Default Theme Color for Chrome on Android Lollipop (Use RGB ColorCode without `#`, e.g.: `db5945`)
theme_color: 7E9576
