# Dependencies
markdown:	kramdown
# Permalinks
permalink:	/blog/:title

# Setup
baseurl: 

title:		Mixed Media Studios
tagline:	'The $5 animation studio'
description:	'Your own personal animation studio'
url:		http://mixedmediastudios.org/
commentsystem:	disqus
  disqus:		mixedmediastudios

author:
  name:		'Mixed Media Studios'
  url:		http://www.mixedmediastudios.org/

paginate:	10
paginate_path: "blog/page:num/"

# Custom vars
icon:		https://avatars1.githubusercontent.com/u/10189614?v=3&s=500
cover:	https://lh4.googleusercontent.com/-d2_moJjARgs/VIzbGUwrF0I/AAAAAAAAAFg/J_500ckvaYc/w1920-h1080-no/cover.jpg
# /Thinny/assets/images/cover.jpg

social:
  - icon:	facebook
    url:	https://facebook.com/TheMixedMediaStudios
    desc:	Follow us on facebook
    
  - icon:	twitter
    url:	https://twitter.com/MixedStudios
    desc:	Follow us on twitter

  - icon:	github
    url:	https://github.com/MixedMediaStudios
    desc:	Fork us on github

  - icon:	googleplus-alt
    url:	https://plus.google.com/b/117832163283159184453/117832163283159184453/
    desc:	Add us on google+

  - icon:	feed
    url:	http://mixedmediastudios.org/atom.xml
    desc:	Subscribe to my feed

menu:
  - title:	Home
    url:	/

  - title:	About
    url:	/about
  - title: Demos
    url: /demo.html
  - title: Blog
    url: /blog/

copyright:
  author:	Mixed Media Studios
  url:		http://www.mixedmediastudios.org
  type_title:	Site design forked from Camporez, some rights reserved
  type_url:	https://github.com/camporez/Thinny

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics: UA-57707910-1

# Default Theme Color for Chrome on Android Lollipop (Use RGB ColorCode without `#`, e.g.: `db5945`)
theme_color: 7E9576
